import STRINGS from '../../config/localizedStrings';

const { LOGIN_TEXT, SIGNUP_TEXT, APP_TITLE, APP_NAME, ACCOUNT_TEXT } = STRINGS;

export const TEXTS = {
  LOGIN: LOGIN_TEXT,
  SIGNUP: SIGNUP_TEXT,
  ACCOUNT: ACCOUNT_TEXT,
  APP_TITLE,
  APP_NAME,
};
