FROM node:10.15.3-stretch-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends git python build-essential && \
    rm -rf /var/lib/apt/lists/* && \
    npm config set unsafe-perm true && \
    npm install mocha -g --loglevel=error

ENV NODE_ENV=production

COPY . /app

WORKDIR /app

ENTRYPOINT ["mocha"]
CMD ["test/selenium/Scenario/newUser.js"]
