import {Given, And, When, Then} from "cypress-cucumber-preprocessor/steps"
const loginButton = '.my-2 > [href="/login"]'

Given ('I am not logged in',()=>{
    cy.visit(Cypress.env('LANDING_PAGE'))
    cy.get('[href="/login"] > .holla-button').click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
})

When ('I traverse through pages',()=>{
    cy.visit(Cypress.env('LANDING_PAGE')+"/summary")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/summary")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/apps")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/wallet")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/transactions")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/security?2fa")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/verification?email")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/settings?signals")
    cy.contains('To view you must login')
    cy.get(loginButton).click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/markets")
    cy.contains("XHT/USDT").click()
    cy.contains('To start trading you must login')
    cy.get(loginButton).first().click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/trade/xht-usdt")
    cy.contains('To start trading you must login')
    cy.get(loginButton).last().click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/trade/xht-usdt")
    cy.contains('To start trading you must login')
    cy.get('[href="/login"] > .holla-button').click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
    cy.visit(Cypress.env('LANDING_PAGE')+"/quick-trade/xht-usdt")
    cy.get('.pairs').contains('XHT/USDT')
    cy.get('.login-container').click()
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
 })

Then ('I can view pages',()=>{
    cy.url().should('eq', Cypress.env('LOGIN_PAGE'))
})
      
  