import STRINGS from '../../config/localizedStrings';

const { ACCOUNTS } = STRINGS;

export const TEXTS = {
  TAB_TITLE: ACCOUNTS.TITLE,
  TAB_VERIFICATION: ACCOUNTS.TAB_VERIFICATION,
  TAB_SECURITY: ACCOUNTS.TAB_SECURITY,
  TAB_NOTIFICATIONS: ACCOUNTS.TAB_NOTIFICATIONS,
  TAB_SETTINGS: ACCOUNTS.TAB_SETTINGS,
}
