import React from 'react';
import moment from 'moment';
import STRINGS from '../../config/localizedStrings';
import { requiredWithCustomMessage, isBefore } from '../../components/Form/validations';
import { InformationSection } from './InformationSection';

export const generateFormValues = (language) => ({
  id: {
    type: {
      type: 'select',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.TYPE_LABEL,
      placeholder: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.TYPE_PLACEHOLDER,
      options: [
        { value: 'id', label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.TYPE_OPTIONS.ID },
        { value: 'passport', label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.TYPE_OPTIONS.OPTIONS },
      ],
      validate: [requiredWithCustomMessage(STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.VALIDATIONS.ID_TYPE)],
    },
    number: {
      type: 'text',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.ID_NUMBER_LABEL,
      placeholder: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.ID_NUMBER_PLACEHOLDER,
      validate: [requiredWithCustomMessage(STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.VALIDATIONS.ID_NUMBER)],
    },
    issued_date: {
      type: 'date-dropdown',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.ISSUED_DATE_LABEL,
      validate: [requiredWithCustomMessage(STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.VALIDATIONS.ISSUED_DATE), isBefore()],
      endDate: moment().add(1, 'days'),
      language,
    },
    expiration_date: {
      type: 'date-dropdown',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.EXPIRATION_DATE_PLACEHOLDER,
      validate: [requiredWithCustomMessage(STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.VALIDATIONS.EXPIRATION_DATE), isBefore()],
      endDate: moment().add(1, 'days'),
      language,
    },
    front: {
      type: 'file',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.FRONT_LABEL,
      placeholder: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.FRONT_PLACEHOLDER,
      validate: [requiredWithCustomMessage(STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.VALIDATIONS.FRONT)],
    },
    back: {
      type: 'file',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.BACK_LABEL,
      placeholder: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.BACK_PLACEHOLDER,
    },
  },
  proofOfResidence: {
    proofOfResidency: {
      type: 'file',
      label: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.POR_LABEL,
      placeholder: STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.FORM_FIELDS.POR_PLACEHOLDER,
      validate: [requiredWithCustomMessage(STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.VALIDATIONS.PROOF_OF_RESIDENCY)],
    },
  },
})

const IdentificationFormSection = () => (
  <InformationSection title={STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.IDENTITY_DOCUMENT}>
    <div>
      {STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.ID_SECTION.TITLE}
      <ul>
        <li>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.ID_SECTION.LIST_ITEM_1}</li>
        <li>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.ID_SECTION.LIST_ITEM_2}</li>
        <li>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.ID_SECTION.LIST_ITEM_3}</li>
      </ul>
    </div>
    <div>
      <div className="warning_text">{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.ID_SECTION.WARNING_1}</div>
      <div>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.ID_SECTION.WARNING_2}</div>
    </div>
  </InformationSection>
);

const PORSection = () => (
  <InformationSection title={STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.PROOF_OF_RESIDENCY}>
    <div>
      {STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_1_TEXT_1}<br />
      {STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_1_TEXT_2}<br />
      {STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_1_TEXT_3}<br />
      {STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_1_TEXT_4}
    </div>
    <div>
      {STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_2_TITLE}
      <ul>
        <li>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_2_LIST_ITEM_1}</li>
        <li>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_2_LIST_ITEM_2}</li>
        <li>{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.SECTION_2_LIST_ITEM_3}</li>
      </ul>
    </div>
    <div className="warning_text">{STRINGS.USER_VERIFICATION.ID_DOCUMENTS_FORM.INFORMATION.POR.WARNING}</div>
  </InformationSection>
);

export const information = {
  id: <IdentificationFormSection />,
  proofOfResidence: <PORSection />,
}
