# Prod HollaEx Kit Docker-Copmose
version: '3'
name: "local"
services:
  hollaex-kit-redis:
    image: redis:8.0.2-alpine
    restart: unless-stopped
    depends_on:
      - hollaex-kit-db
    ports:
      - 6379:6379
    env_file:
      - hollaex-kit.env
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    networks:
      - hollaex-kit-network
  hollaex-kit-db:
    image: postgres:14.9-alpine
    restart: unless-stopped
    volumes:
      - hollaex_db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - hollaex-kit.env
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 600M
        reservations:
          cpus: "0.1"
          memory: 300M
    command: ["sh", "-c", "export POSTGRES_DB=$${DB_NAME} && export POSTGRES_USER=$${DB_USERNAME} && export POSTGRES_PASSWORD=$${DB_PASSWORD} && ln -sf /usr/local/bin/docker-entrypoint.sh ./docker-entrypoint.sh && ./docker-entrypoint.sh postgres"]
    networks:
      - hollaex-kit-network
  hollaex-kit-server-api:
    image: hollaex/hollaex-kit:2.11.4-cli-deprecation-46ea26c
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: unless-stopped
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.1"
          memory: 512M
    command:
      - app.js
    ports:
      - 10010:10010
    networks:
      - hollaex-kit-network
    depends_on:
      - hollaex-kit-redis
      - hollaex-kit-db
  hollaex-kit-server-stream:
    image: hollaex/hollaex-kit:2.11.4-cli-deprecation-46ea26c
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: unless-stopped
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    command:
      - ws/index.js
    ports:
      - 10080:10080
    networks:
      - hollaex-kit-network
    depends_on:
      - hollaex-kit-server-api
      - hollaex-kit-redis
      - hollaex-kit-db
  hollaex-kit-server-plugins:
    image: hollaex/hollaex-kit:2.11.4-cli-deprecation-46ea26c
    build:
      context: .
      dockerfile: tools/Dockerfile
    restart: unless-stopped
    env_file:
      - hollaex-kit.env
    entrypoint:
      - node
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1200M
        reservations:
          cpus: "0.1"
          memory: 700M
    command:
      - plugins/index.js
      - 10011:10011
    networks:
      - hollaex-kit-network
    depends_on:
      - hollaex-kit-server-api
      - hollaex-kit-redis
      - hollaex-kit-db
networks:
  hollaex-kit-network:
volumes:
  hollaex_db_vol:
