import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
   en: {
     APP_TITLE: 'exir-exchange',
     APP_NAME: 'exir',
     FIAT_NAME: 'Dollar',
     FIAT_FULLNAME: 'United States Dollar',
     FIAT_SHORTNAME: 'USD',
     FIAT_CURRENCY_SYMBOL: '$',
     BTC_NAME: 'Bitcoin',
     BTC_FULLNAME: 'Bitcoin',
     BTC_SHORTNAME: 'BTC',
     TIMESTAMP_FORMAT: 'YYYY/MM/DD HH:mm:ss A',
     HOUR_FORMAT: 'HH:mm:ss A',
     LOGIN_TEXT: 'Login',
     SIGNUP_TEXT: 'Sign Up',
     REGISTER_TEXT: 'Register',
     ACCOUNT_TEXT: 'Account',
     CLOSE_TEXT: 'Close',
     COPY_TEXT: 'Copy',
     UPLOAD_TEXT: 'Upload',
     CONTACT_US_TEXT: 'Contact us',
     NEED_HELP_TEXT: 'Need help',
     HELP_TEXT: 'help',
     SUCCESS_TEXT: 'Success',
     ERROR_TEXT: 'Error',
     NO_OPTIONS: 'No options availables',
     HOME: {
       SECTION_1_TITLE: 'Buy & sell cryptocurrencies',
       SECTION_1_TEXT_1: 'EXIR is a cryptocurrency exchange where you can buy and sell bitcoins and other digital currencies.',
       SECTION_1_TEXT_2: 'We strive to bring the digital enconomy forward through afforable and simple access to future currencies.',
       SECTION_1_BUTTON_1: 'Learn more',
       SECTION_3_TITLE: 'Features',
       SECTION_3_CARD_1_TITLE: 'PAYMENT OPTIONS',
       SECTION_3_CARD_1_TEXT: 'Most popular methods: Visa, MasterCard, bank transfer (SWIFT, SEPA), cryptocurrency',
       SECTION_3_CARD_2_TITLE: 'ADVANCED REPORTING',
       SECTION_3_CARD_2_TEXT: 'Downloadable reports, real-time balance, transaction history with transparent fees',
       SECTION_3_CARD_3_TITLE: 'STRONG SECURITY',
       SECTION_3_CARD_3_TEXT: 'Protection against DDoS attacks, full data encryption, compliant with PCI DSS standard',
       SECTION_3_CARD_4_TITLE: 'MARGIN TRADING',
       SECTION_3_CARD_4_TEXT: '1:2 and 1:3 leverages, automatic funds borrowing, no extra accounts needed, negative balance protection.',
       SECTION_3_CARD_5_TITLE: 'HIGH LIQUIDITY',
       SECTION_3_CARD_5_TEXT: 'Fast order execution, low spread, access to high liquidity orderbook for top currency pairs',
       SECTION_3_CARD_6_TITLE: 'LEGAL COMPLIANCE',
       SECTION_3_CARD_6_TEXT: 'Registration in UK, MSB status in FinCEN, essential licenses and strong relations with banks',
       SECTION_3_BUTTON_1: 'View Demo',
     },
     FOOTER: {
       FOOTER_LEGAL: [
         'Registration on or use of this site constitutes acceptance of our',
         'Terms of Service and Privacy Policy.',
         'Disclaimer Commerce Policy Made in NYC',
         'Stock quotes by finanzen.net',
       ],
       FOOTER_LANGUAGE_TEXT: 'LANGUAGE',
       FOOTER_LANGUAGE_LANGUAGES: [
         { key: 'en', label: 'ENGLISH' },
         { key: 'fa', label: 'فارسی' },
       ],
       FOOTER_COPYRIGHT: 'COPYRIGHT 2017',
       SECTIONS: {
         SECTION_1_TITLE: 'SERVICES',
         SECTION_1_LINK_1: 'Buy Bitcoins',
         SECTION_1_LINK_2: 'Buy Ethereum',
         SECTION_1_LINK_3: 'Sell Bitcoins',
         SECTION_1_LINK_4: 'Bitcoin Trading',
         SECTION_1_LINK_5: 'Margin Trading',
         SECTION_2_TITLE: 'INFORMATION',
         SECTION_2_LINK_1: 'Payment Options',
         SECTION_2_LINK_2: 'Fee Schedule',
         SECTION_2_LINK_3: 'Getting Started',
         SECTION_2_LINK_4: 'Identity Verification Guide',
         SECTION_2_LINK_5: 'Card Verification Guide',
         SECTION_3_TITLE: 'TOOLS',
         SECTION_3_LINK_1: 'API',
         SECTION_3_LINK_2: 'Bitcoin Calculator',
         SECTION_3_LINK_3: 'Bitcoin Price Widget',
         SECTION_3_LINK_4: 'Mobile App',
         SECTION_3_LINK_5: 'Affiliate Program',
         SECTION_3_LINK_6: 'Donations',
         SECTION_4_TITLE: 'ABOUT',
         SECTION_4_LINK_1: 'About Us',
         SECTION_4_LINK_2: 'Legal & Security',
         SECTION_4_LINK_3: 'Terms of Use',
         SECTION_4_LINK_4: 'Refund Policy',
         SECTION_4_LINK_5: 'Press',
         SECTION_4_LINK_6: 'Blog',
         SECTION_4_LINK_7: 'Help Center',
       }
     },
     ACCOUNTS: {
       TITLE: 'Account',
       TAB_VERIFICATION: 'Verification',
       TAB_SECURITY: 'Security',
       TAB_NOTIFICATIONS: 'Notifications',
       TAB_SETTINGS: 'Settings',
     },
     CONTACT_FORM: {
       CATEGORY_LABEL: 'Category',
       CATEGORY_PLACEHOLDER: 'Select the category that best suits your issue',
       CATEGORY_OPTIONS: {
         OPTION_VERIFY: 'Verification',
         OPTION_BUG: 'Bug',
       },
       SUBJECT_LABEL: 'Subject',
       SUBJECT_PLACEHOLDER: 'Type the subject of your issue',
       DESCRIPTION_LABEL: 'Description',
       DESCRIPTION_PLACEHOLDER: 'Type in detail what the issue is',
       ATTACHMENT_LABEL: 'Add an attachment',
       ATTACHMENT_PLACEHOLDER: 'Add a file to help communicate your issue. PDF, JPG, PNG and GIF files are accepted',
     },
     DEPOSIT: {
       CRYPTO_LABELS: {
         BTC: 'Your Bitcoin receiving address',
       },
       INFORMATION_MESSAGES: [
         'Use the bank details below to deposit USD in to your account. Transfers usally take up to 1-2 business day.',
         'Deposits will only be accepeted from a bank account in a name that matches the name registered with your Exir account.',
       ],
       LIMIT_MESSAGE: 'Daily deposit max amount',
       INCREASE_LIMIT: 'Want to increase your daily limit?',
       QR_CODE: 'This QR Code can be scanned by the person who wants to send you Bitcoins',
       NO_DATA: 'No information available',
     },
     LOGIN: {
       LOGIN_TO: 'Login to {0}',
       CANT_LOGIN: 'Can\'t login?',
       NO_ACCOUNT: 'Don\'t have an account?',
       CREATE_ACCOUNT: 'Create one here',
       HELP: 'Help',
     },
     FORM_FIELDS: {
       EMAIL_LABEL: 'Email',
       EMAIL_PLACEHOLDER: 'Type your Email address',
       PASSWORD_LABEL: 'Password',
       PASSWORD_PLACEHOLDER: 'Type your password',
       PASSWORD_REPEAT_LABEL: 'Retype your password',
       PASSWORD_REPEAT_PLACEHOLDER: 'Retype your password',
     },
     VALIDATIONS: {
      OTP_LOGIN: 'Provide OTP code to login',
      INVALID_EMAIL: 'Invalid email address',
      TYPE_EMAIL: 'Type your E-mail',
      REQUIRED: 'Required field',
      INVALID_DATE: 'Invalid date',
      INVALID_PASSWORD: 'Invalid password. It has to contain at least 8 characters, a digit in the password and a special character.',
      INVALID_CURRENCY: 'Invalid {0} address ({1})',
      INVALID_BALANCE: 'Insufficient balance available ({0}) to perform the operation ({1}).',
      MIN_VALUE: 'Value must be {0} or higher.',
      MAX_VALUE: 'Value must be {0} or lower.',
      INSUFFICIENT_BALANCE: 'Insufficient balance',
      PASSWORDS_DONT_MATCH: 'Password don\'t match',
      USER_EXIST: 'Email has already been registered',
      ACCEPT_TERMS: 'You have not agreed to the Terms of use and Privacy Policy',
    },
    LEGAL: {
      PRIVACY_POLICY: {
        TITLE: 'Privacy Policy',
        SUBTITLE: 'Last updated April 1, 2017. Replaces the prior version in its entirety.',
        TEXTS: [
          'BitMEX (website: https://www.BitMEX.com) is a Bitcoin-based virtual trading platform that is wholly owned by HDR Global Trading Limited. HDR Global Trading Limited (hereinafter referred to as BitMEX) was incorporated under the International Business Companies Act of 1994 of the Republic of Seychelles with a company number of 148707.',
          'Use of this BitMEX website (“Website”) and the service offered on the Website (“Service”) are governed by the terms contained on this Terms and Conditions page (“Terms”). This agreement entirely constitutes the agreement between the parties. All other information provided on the Website or oral/written statements made are excluded from this agreement; the exchange policy is provided for guidance only and does not constitute a legal agreement between the parties.',
          'By accessing, viewing or downloading information from the Website and using the Service provided by BitMEX you acknowledge that you have read, understand, and unconditionally agree to be bound by these Terms. BitMEX may at any time, without notice, amend the Terms. You agree to continue to be bound by any amended terms and conditions and that BitMEX has no obligation to notify you of such amendments. You acknowledge that it is your responsibility to check these Terms periodically for changes and that your continued use of the Website and Services offered by BitMEX following the posting of any changes to the Terms indicates your acceptance of any such changes.',
          'The Website and the copyright in all text, graphics, images, software and any other materials on the Website is owned by BitMEX including all trademarks and other intellectual property rights in respect of materials and Service on the Website. Materials on this Website may only be used for personal use and non-commercial purposes.',
          'You may display on a computer screen or print extracts from the Website for the above-stated purpose only provided that you retain any copyright and other proprietary notices or any BitMEX trademarks or logos, as shown on the initial printout or download without alteration, addition or deletion. Except as expressly stated herein, you may not without BitMEX’s prior written permission alter, modify, reproduce, distribute or use in any other commercial context any materials from the Website.',
          'You acknowledge that ‘BitMEX’ and the BitMEX logo are trademarks of HDR Global Trading Limited. You may reproduce such trademarks without alteration on material downloaded from this Website to the extent authorised above, but you may not otherwise use, copy, adapt or erase them.',
          'You shall not in any circumstances obtain any rights over or in respect of the Website (other than rights to use the Website pursuant to these Terms and any other terms and conditions governing a particular service or section of the Website) or hold yourself out as having any such rights over or in respect of the Website.',
        ],
      },
      GENERAL_TERMS: {
        TITLE: 'General Terms of Service',
        SUBTITLE: 'Last updated April 1, 2017. Replaces the prior version in its entirety.',
        TEXTS: [
          'BitMEX (website: https://www.BitMEX.com) is a Bitcoin-based virtual trading platform that is wholly owned by HDR Global Trading Limited. HDR Global Trading Limited (hereinafter referred to as BitMEX) was incorporated under the International Business Companies Act of 1994 of the Republic of Seychelles with a company number of 148707.',
          'Use of this BitMEX website (“Website”) and the service offered on the Website (“Service”) are governed by the terms contained on this Terms and Conditions page (“Terms”). This agreement entirely constitutes the agreement between the parties. All other information provided on the Website or oral/written statements made are excluded from this agreement; the exchange policy is provided for guidance only and does not constitute a legal agreement between the parties.',
          'By accessing, viewing or downloading information from the Website and using the Service provided by BitMEX you acknowledge that you have read, understand, and unconditionally agree to be bound by these Terms. BitMEX may at any time, without notice, amend the Terms. You agree to continue to be bound by any amended terms and conditions and that BitMEX has no obligation to notify you of such amendments. You acknowledge that it is your responsibility to check these Terms periodically for changes and that your continued use of the Website and Services offered by BitMEX following the posting of any changes to the Terms indicates your acceptance of any such changes.',
          'The Website and the copyright in all text, graphics, images, software and any other materials on the Website is owned by BitMEX including all trademarks and other intellectual property rights in respect of materials and Service on the Website. Materials on this Website may only be used for personal use and non-commercial purposes.',
          'You may display on a computer screen or print extracts from the Website for the above-stated purpose only provided that you retain any copyright and other proprietary notices or any BitMEX trademarks or logos, as shown on the initial printout or download without alteration, addition or deletion. Except as expressly stated herein, you may not without BitMEX’s prior written permission alter, modify, reproduce, distribute or use in any other commercial context any materials from the Website.',
          'You acknowledge that ‘BitMEX’ and the BitMEX logo are trademarks of HDR Global Trading Limited. You may reproduce such trademarks without alteration on material downloaded from this Website to the extent authorised above, but you may not otherwise use, copy, adapt or erase them.',
          'You shall not in any circumstances obtain any rights over or in respect of the Website (other than rights to use the Website pursuant to these Terms and any other terms and conditions governing a particular service or section of the Website) or hold yourself out as having any such rights over or in respect of the Website.',
        ]
      },
    },
    NOTIFICATIONS: {
      BUTTONS: {
        OKAY: 'Okay',
        START_TRADING: 'start trading',
        SEE_HISTORY: 'see history',
      },
      DEPOSITS: {
        FIAT: {
          TITLE: '{0} Deposit receieved',
          SUBTITLE: 'You’ve receieved your {0} deposit',
        },
        BTC: {
          TITLE_RECEIVED: '{0} Deposit receieved',
          TITLE_INCOMING: 'Incoming {0}',
          SUBTITLE_RECEIVED: 'You’ve receieved your {0} deposit',
          SUBTITLE_INCOMING: 'You have incoming {0}',
          INFORMATION_PENDING_1: 'Your {0} require 3 confirmations before you can begin trading.',
          INFORMATION_PENDING_2: 'This may take 20-40 minutes. We will send an email once your {0} have completed Confirming.',
        }
      },
    },
    OTP_FORM: {
      OTP_LABEL: 'OTP Code',
      OTP_PLACEHOLDER: 'Enter the authentication code',
      OTP_TITLE: 'Authenticator Code',
      OTP_HELP: 'help',
      OTP_BUTTON: 'submit',
    },
    QUICK_TRADE: {
      TITLE: 'Quick',
      TOTAL_COST: 'Total cost',
      BUTTON: 'Review {0} order',
      INPUT: '{0}s to {1}',
      SIDES: [
        'buy',
        'sell',
      ],
    },
    PREVIOUS_PAGE: 'previous page',
    NEXT_PAGE: 'next page',
    WALLET: {
      TOTAL_ASSETS: 'Total Assets',
      AVAILABLE_WITHDRAWAL: 'Available for trading',
      AVAILABLE_TRADING: 'Available for withdrawal',
      ORDERS_PLURAL: 'orders',
      ORDERS_SINGULAR: 'order',
      HOLD_ORDERS: 'You have {0} open {1}, resulting in a hold of {2}{3} placed on your {4} balance',
    },
    REQUEST_RESET_PASSWORD: {
      TITLE: 'Account Recovery',
      SUBTITLE: `Recover your account below`,
      SUPPORT: 'Contact Support',
      BUTTON: 'Send recovery link',
    },
    REQUEST_RESET_PASSWORD_SUCCESS: {
      TITLE: 'Password reset sent',
      TEXT: 'If an account exists for the email address, an email has been sent to it with reset instructions. Please check your email and click the link to complete your password reset.',
    },
    RESET_PASSWORD: {
      TITLE: 'Set new password',
      SUBTITLE: 'Set new password',
      BUTTON: 'Set new password',
    },
    RESET_PASSWORD_SUCCESS: {
      TEXT_1: 'You’ve successfully set up a new password.',
      TEXT_2: 'Click login below to proceed.',
    },
    SIGN_UP: {
      SIGNUP_TO: 'Sign up to {0}',
      NO_EMAIL: 'Haven\'t receieved the email?',
      REQUEST_EMAIL: 'Request another one here',
      TERMS: {
        terms: 'General Terms',
        policy: 'Privacy Policy',
        text: 'I have read and agree to the {0} and {1}.'
      }
    },
    VERIFICATION_TEXTS: {
      TITLE: 'verification sent',
      TEXT_1: 'Check your email and click the link to verifiy yourself.',
      TEXT_2: 'If you have not receieved any email verification and you have checked your junk mail then you can try clicking resend below.',
    },
    VERIFICATION_EMAIL_REQUEST: {
      TITLE: 'Activation Email Request',
      BUTTON: 'Request Email'
    },
    VERIFICATION_EMAIL_REQUEST_SUCCESS: {
      TITLE: 'Verification reset send',
      TEXT_1: 'If after a few minutes you still have not receieved an email verification then please contact us below.',
    },
    VERIFICATION_EMAIL: {
      INVALID_UUID: 'Invalid code',
      TEXT_1: 'You\'ve successfully verified your email.',
      TEXT_2: 'You can now proceed to login',
    }
  },
  fa: {

  }
});

export default strings;
