import flatten from 'flat';

const options = { safe: true }
const nestedIcons = {
  EXCHANGE_LOGO_LIGHT: '',
  EXCHANGE_LOGO_DARK: '',
  FAV_ICON: '/favicon.ico',
  LOADER_LIGHT: '/assets/loader-light.gif',
  LOADER_DARK: '/assets/loader-dark.gif',
  BOARDING_IMAGE_LIGHT: '/assets/background.png',
  BOARDING_IMAGE_DARK: '/assets/dark-background.jpg',
  TRADE_HISTORY_DARK: '/assets/icons/trade-history-dark.svg',
  TRADE_HISTORY_LIGHT: '/assets/icons/trade-history-light.svg',
  ACTIVE_TRADE_DARK: '/assets/icons/active-trade-dark.svg',
  ACTIVE_TRADE_LIGHT: '/assets/icons/active-trade-light.svg',
  DEMO_LOGIN_ICON_DARK: '/assets/icons/demo-login-icon-dark.svg',
  DEMO_LOGIN_ICON_LIGHT: '/assets/icons/demo-login-icon-light.svg',
  CANCEL_WITHDRAW_DARK: '/assets/icons/cancel-withdraw-dark-02-03.svg',
  CANCEL_WITHDRAW_LIGHT: '/assets/icons/cancel-withdraw-light-02.svg',
  BTC_ICON_DARK: '/assets/icons/btc-icon-dark-01.svg',
  BTC_ICON: '/assets/icons/btc-icon-01.svg',
  ETH_ICON: '/assets/icons/eth-icon-01.svg',
  ETH_ICON_DARK: '/assets/icons/eth-icon-dark-01.svg',
  EUR_ICON: '/assets/icons/eur-icon.svg',
  LTC_ICON: '/assets/icons/ltc-icon.svg',
  LTC_ICON_DARK: '/assets/icons/ltc-icon.svg',
  TRX_ICON: '/assets/icons/trx-icon.svg',
  TRX_ICON_DARK: '/assets/icons/trx-icon.svg',
  TUSD_ICON: '/assets/icons/tusd-icon.svg',
  TUSD_ICON_DARK: '/assets/icons/tusd-icon.svg',
  XLM_ICON: '/assets/icons/xlm-icon.svg',
  XLM_ICON_DARK: '/assets/icons/xlm-icon.svg',
  EOS_ICON: '/assets/icons/eos-icon.svg',
  EOS_ICON_DARK: '/assets/icons/eos-icon.svg',
  DAI_ICON: '/assets/icons/dai-icon.svg',
  DAI_ICON_DARK: '/assets/icons/dai-icon.svg',
  BNB_ICON: '/assets/icons/bnb-icon.svg',
  BNB_ICON_DARK: '/assets/icons/bnb-icon.svg',
  ADA_ICON: '/assets/icons/ada-icon.svg',
  ADA_ICON_DARK: '/assets/icons/ada-icon.svg',
  LIFESAVER: '/assets/acounts/account-icons-05.svg',
  CONTACT_US_ICON: '/assets/acounts/help-contact-us-01.svg',
  QUESTION_MARK: '/assets/icons/question-mark-black.svg',
  QUESTION_MARK_COLOR: '/assets/icons/question-mark-color.svg',
  LAPTOP: '/assets/icons/compute-play-black.svg',
  LAPTOP_COLOR: '/assets/icons/compute-play-color.svg',
  TELEGRAM: '/assets/icons/telegram-black.svg',
  TELEGRAM_COLOR: '/assets/icons/telegram-color.svg',
  BCH_ICON: '/assets/icons/bch-icon.svg',
  BCH_ICON_DARK: '/assets/icons/bch-icon.svg',
  BCH_NAV_ICON: '/assets/icons/bch-icon-nav.svg',
  XRP_ICON: '/assets/icons/xrp-icon-01.svg',
  XRP_ICON_DARK: '/assets/icons/xrp-icon-01.svg',
  XRP_NAV_ICON: '/assets/icons/xrp-icon-01.svg',
  KRW_ICON: '/assets/icons/krw-icon-01.svg',
  XHT_ICON: '/assets/icons/xht-icon.svg',
  XHT_ICON_DARK: '/assets/icons/xht-icon-dark.svg',
  XMR_ICON: '/assets/icons/xmr-icon.svg',
  XMR_ICON_DARK: '/assets/icons/xmr-icon-dark.svg',
  USDT_ICON: '/assets/icons/usdt-icon.svg',
  CHECK: '/assets/images/Orderbook scrolling-01.svg',
  DARK_CHECK: '/assets/images/dark-Orderbook-scrolling-01.svg',
  BLUE_QUESTION: '/assets/acounts/account-icons-08.svg',
  RED_WARNING: '/assets/acounts/account-icons-09.svg',
  GENDER_F: '/assets/acounts/account-icons-10.svg',
  GENDER_M: '/assets/acounts/account-icons-11.svg',
  GENDER_FEMALE: '/assets/acounts/account-icons-26.svg',
  GENDER_MALE: '/assets/acounts/account-icons-27.svg',
  BITCOIN_CLEAR: '/assets/acounts/account-icons-13.svg',
  RED_ARROW: '/assets/acounts/account-icons-16.svg',
  BLUE_CLIP: '/assets/acounts/account-icons-17.svg',
  BLACK_CHECK: '/assets/acounts/account-icons-19.svg',
  KEYS: '/assets/acounts/account-icons-22.svg',
  OTP_KEYS: '/assets/acounts/account-icons-29.svg',
  GREEN_CHECK: '/assets/acounts/account-icons-23.svg',
  LETTER: '/assets/acounts/account-icons-24.svg',
  SQUARE_DOTS: '/assets/acounts/account-icons-25.svg',
  OTP_CODE: '/assets/acounts/account-icons-28.svg',
  COPY_NEW: '/assets/images/copy.svg',
  COPY_NOTIFICATION: '/assets/images/copy-icon-snack-notification.svg',
  ACCOUNT_LINE: '/assets/images/account.svg',
  ACCOUNT_RECOVERY: '/assets/images/account-recovery.svg',
  BITCOIN_WALLET: '/assets/images/bitcoin-wallet.svg',
  CHECK_SENDING_BITCOIN: '/assets/images/check-sending-bitcoin.svg',
  DATA: '/assets/images/data.svg',
  DEPOSIT_BITCOIN: '/assets/images/deposit-bitcoin-dark-theme.svg',
  DEPOSIT_HISTORY: '/assets/images/deposit-history.svg',
  DEPOSIT_HISTORY_GREY: '/assets/images/deposit-history-grey.svg',
  DEPOSIT_RECEIVED_BITCOIN: '/assets/images/deposit-received-bitcoin.svg',
  DEPOSIT_SUCCESS: '/assets/images/D-W-Success.svg',
  WITHDRAWAL_SUCCESS: '/assets/images/D-W-Success.svg',
  EMAIL: '/assets/images/email.svg',
  EMAIL_SENT: '/assets/images/email-sent.svg',
  OTP_DOTS: '/assets/images/f2fa-pin.svg',
  DEPOSIT_BASE: '/assets/images/fiat-deposit.svg',
  DEPOSIT_BASE_COIN_COMPLETE: '/assets/images/fiat-deposit-completed.svg',
  BASE_WALLET: '/assets/images/fiat-wallet.svg',
  GEAR_BLACK: '/assets/images/gear.svg',
  GEAR_GREY: '/assets/images/gear-grey.svg',
  HELP_ICON: '/assets/images/help.svg',
  ID_BLACK: '/assets/images/id.svg',
  ID_GREY: '/assets/images/id-grey.svg',
  INCOMING_BITCOIN: '/assets/images/Incoming-bitcoin.svg',
  INCOMING_BTC: '/assets/images/incoming-btc.svg',
  INCOMING_TOMAN: '/assets/images/incoming-toman.svg',
  LICENSE: '/assets/images/licence.svg',
  LIQUID: '/assets/images/liquid.svg',
  MARGIN: '/assets/images/margin.svg',
  PASSWORD_RESET: '/assets/images/password-reset.svg',
  PAYMENT_OPTIONS: '/assets/images/payment-options.svg',
  QUICK_TRADE: '/assets/images/quick-trade.svg',
  QUICK_TRADE_TAB: '/assets/images/quick-trade-tab.svg',
  QUICK_TRADE_TAB_ACTIVE: '/assets/images/quick-trade-tab-active.svg',
  QUICK_TRADE_INSUFFICIENT_FUND: '/assets/icons/quick-trade-insufficient-funds.svg',
  QUICK_TRADE_SUCCESSFUL: '/assets/icons/quick-trade-success-coin-pile.svg',
  SECURE: '/assets/images/secure.svg',
  SECURITY_BLACK: '/assets/images/security.svg',
  SECURITY_GREY: '/assets/images/security-grey.svg',
  SET_NEW_PASSWORD: '/assets/images/set-new-password.svg',
  SUCCESS_BLACK: '/assets/images/success-black.svg',
  TRADE_HISTORY: '/assets/images/trade-history.svg',
  TRADE_HISTORY_GREY: '/assets/images/trade-history-grey.svg',
  TRADES_ICON: '/assets/images/trade-history.svg',
  TRADE_SUCCESS: '/assets/images/trade-success.svg',
  TRANSACTION_HISTORY: '/assets/images/transaction-history.svg',
  UPDATE_QUICK_TRADE: '/assets/images/update-quick-trade.svg',
  VERIFICATION_SENT: '/assets/images/resend-email-light.svg',
  VERIFICATION_SENT_DARK: '/assets/images/resend-email.svg',
  WITHDRAW: '/assets/images/withdraw.svg',
  WITHDRAW_HISTORY: '/assets/images/withdraw-history.svg',
  WITHDRAW_HISTORY_GREY: '/assets/images/withdraw-history-grey.svg',
  BLUE_ARROW_LEFT: '/assets/images/blue-arrow-left.svg',
  BLUE_ARROW_RIGHT: '/assets/images/blue-arrow-right.svg',
  SESSION_TIMED_OUT: '/assets/images/session-timed-out.svg',
  BLUE_EDIT: '/assets/images/blue-edit-exir-icon.svg',
  BLUE_PLUS: '/assets/images/max-plus-blue-icon.svg',
  BLUE_TIMER: '/assets/images/timer-icon.svg',
  DROPDOWN_ARROW: '/assets/images/down-arrow-home.svg',
  NOTIFICATION_ORDER_LIMIT_BUY_FILLED:
    '/assets/images/limit-buy-order-filled-01.svg',
  NOTIFICATION_ORDER_LIMIT_BUY_CREATED:
    '/assets/images/limit-buy-order-icon-01.svg',
  NOTIFICATION_ORDER_LIMIT_BUY_FILLED_PART:
    '/assets/images/limit-buy-order-part-filled-01.svg',
  NOTIFICATION_ORDER_LIMIT_SELL_FILLED:
    '/assets/images/limit-sell-order-filled-01.svg',
  NOTIFICATION_ORDER_LIMIT_SELL_CREATED:
    '/assets/images/limit-sell-order-icon-01.svg',
  NOTIFICATION_ORDER_LIMIT_SELL_FILLED_PART:
    '/assets/images/limit-sell-order-part-filled-01.svg',
  NOTIFICATION_ORDER_MARKET_BUY_FILLED: '/assets/images/market-buy-01.svg',
  NOTIFICATION_ORDER_MARKET_SELL_FILLED: '/assets/images/market-sell-01.svg',
  NOTIFICATION_VERIFICATION_WARNING: '/assets/images/verification.svg',
  LOGOUT_ARROW: '/assets/images/logout-arrow-active.svg',
  LOGOUT_ARROW_GREY: '/assets/images/logout-arrow.svg',
  VERIFICATION_WARNING: '/assets/images/astrics.svg',
  VERIFICATION_SUCCESS: '/assets/images/success-check-box.svg',
  VERIFICATION_DOC: '/assets/images/doc.svg',
  VERIFICATION_DOC_INACTIVE: '/assets/images/doc-inactive.svg',
  VERIFICATION_EMAIL: '/assets/images/email_2.svg',
  VERIFICATION_EMAIL_INACTIVE: '/assets/images/email-inactive.svg',
  VERIFICATION_MOBILE: '/assets/images/mobile.svg',
  VERIFICATION_MOBILE_INACTIVE: '/assets/images/mobile-inactive.svg',
  VERIFICATION_BANK: '/assets/images/bank.svg',
  VERIFICATION_BANK_INACTIVE: '/assets/images/bank-inactive.svg',
  VERIFICATION_ID: '/assets/images/id_2.svg',
  VERIFICATION_ID_INACTIVE: '/assets/images/id_2-inactive.svg',
  COIN_WITHDRAW_BTC: '/assets/images/coin-withdraw-btc.svg',
  COIN_WITHDRAW_TOMAN: '/assets/images/coin-withdraw-tom.svg',
  LOGOUT_DOOR_ACTIVE: '/assets/images/logout-door-active.svg',
  LOGOUT_DOOR_INACTIVE: '/assets/images/logout-door-inactive.svg',
  CANCEL_CROSS_ACTIVE: '/assets/images/cancel-cross-active.svg',
  CANCEL_CROSS_INACTIVE: '/assets/images/cancel-cross-inactive.svg',
  SIDEBAR_WALLET_ACTIVE_1: '/assets/images/wallet-active.svg',
  SIDEBAR_WALLET_INACTIVE_1: '/assets/images/wallet-inactive.svg',
  SIDEBAR_WALLET_ACTIVE: '/assets/images/wallet-selected.svg',
  SIDEBAR_WALLET_INACTIVE: '/assets/images/wallet.svg',
  SIDEBAR_ACCOUNT_ACTIVE: '/assets/images/account_2-active.svg',
  SIDEBAR_ACCOUNT_INACTIVE: '/assets/images/account_2-inactive.svg',
  SIDEBAR_HOME_ACTIVE: '/assets/images/home-active.svg', // new
  SIDEBAR_HOME_ACTIVE_INACTIVE: '/assets/images/home-tab-inactive.svg', // new
  SIDEBAR_POST_ACTIVE: '/assets/images/post-active.svg',
  SIDEBAR_POST_INACTIVE: '/assets/imagespost-inactive.svg',
  SIDEBAR_TRADING_ACTIVE: '/assets/images/trade-active.svg',
  SIDEBAR_TRADING_INACTIVE: '/assets/images/trade-inactive.svg',
  SIDEBAR_QUICK_TRADING_ACTIVE:
    '/assets/images/quick-trade-tab-selected-01.svg',
  SIDEBAR_QUICK_TRADING_INACTIVE: '/assets/images/quick-trade-tab-01-01.svg',
  SIDEBAR_ADMIN_DASH_ACTIVE: '/assets/images/admin-dash-icon.svg',
  ARROW_TRANSFER_HISTORY_ACTIVE:
    '/assets/images/arrow-trans-history-active.svg',
  ARROW_TRANSFER_HISTORY_INACTIVE: '/assets/images/arrow-trans-history.svg',
  ARROW_DOWN: '/assets/images/arrow-down.svg',
  TOKENS_INACTIVE: '/assets/images/dev-icon.svg',
  TOKENS_ACTIVE: '/assets/images/dev-icon.svg',
  TOKEN_REVOKED: '/assets/images/api-key-revoked.svg',
  TOKEN_ACTIVE: '/assets/images/api-key-active.svg',
  TOKEN_TRASHED: '/assets/images/api-key-trashed.svg',
  TOKEN_GENERATE: '/assets/images/api-key-generate.svg',
  TOKEN_GENERATE_DARK: '/assets/images/api-key-generate-dark.svg',
  TOKEN_CREATED: '/assets/images/api-key-created.svg',
  TOKEN_CREATED_DARK: '/assets/images/api-key-created-dark.svg',
  CHECK_ORDER: '/assets/images/check-order-popup-01.svg',
  ITEM_OPTIONS: '/assets/images/item-options.svg',
  DOTTED_GRIP: '/assets/images/dotted-grip-chat-repeat-pattern.svg',
  CHAT: '/assets/images/chat-icon.svg',
  WITHDRAW_MAIL_CONFIRMATION: '/assets/images/withdraw-mail-confirmation.svg',
  CLOSE_CROSS: '/assets/images/close-cross-tab.svg',
  TAB_PLUS: '/assets/images/tab-plus.svg',
  TAB_MINUS: '/assets/images/tab-minus.svg',
  TAB_SUMMARY: '/assets/images/tab-summary.svg',
  TAB_HISTORY: '/assets/images/tab-history.svg',
  TAB_WALLET: '/assets/images/tab-wallet.svg',
  TAB_SECURITY: '/assets/images/tab-security.svg',
  TAB_VERIFY: '/assets/images/tab-verify.svg',
  TAB_SETTING: '/assets/images/tab-setting.svg',
  TAB_API: '/assets/images/tab-api.svg',
  TRADE_FILLED_SUCESSFUL: '/assets/images/Orderbook scrolling-01.svg',
  TRADE_PARTIALLY_FILLED: '/assets/images/part-fill.svg',
  TAB_SIGNOUT: '/assets/images/signout.svg',
  DOUBLE_ARROW: '/assets/images/double-arrow.svg',
  SEARCH: '/assets/images/search.svg',
  VERIFICATION_DOC_STATUS: '/assets/images/verification-doc-status.svg',
  VERIFICATION_PENDING: '/assets/images/verification-pending-orange.svg',
  VERIFICATION_REJECTED:
    '/assets/images/verification-rejected-yellow-cross.svg',
  VERIFICATION_INCOMPLETE: '/assets/images/verification-attention-red.svg',
  VERIFICATION_VERIFIED: '/assets/images/verification-green-tick.svg',
  VERIFICATION_EMAIL_NEW: '/assets/images/verification-email.svg',
  VERIFICATION_PHONE_NEW: '/assets/images/verification-phone.svg',
  VERIFICATION_ID_NEW: '/assets/images/verification-id.svg',
  VERIFICATION_BANK_NEW: '/assets/images/verification-bank.svg',
  VERIFICATION_DOCUMENT_NEW: '/assets/images/verification-document.svg',
  PENDING_TIMER: '/assets/images/pending-timer.svg',
  VOLUME_PENDING: '/assets/images/volume-pending-icon.svg',
  VOLUME_PENDING_DARK: '/assets/images/volume-pending-dark.svg',
  SELF_KYC_ID_EN: '/assets/self-kyc-id-note-english.png',
  CHAT_ICON_LVL_3: '/assets/images/kraken-chat-lvl-3.svg',
  CHAT_ICON_LVL_4: '/assets/images/whale-chat-lvl-4.svg',
  CHAT_ICON_SPECIAL: '/assets/images/fin-chat-special.svg',
  NOTE_KYC: '/assets/images/note-KYC.svg',
  SIDEBAR_CHAT: '/assets/images/bottom-chat-icon.svg',
  SIDEBAR_HELP: '/assets/images/help-question-mark-icon.svg',
  CONNECT_LOADING: '/assets/images/connect-loading.svg',
  KRAKEN: '/assets/images/cunning-blue-kraken-trader.svg',
  SNAPPER: '/assets/images/little-red-snapper-trader.svg',
  SHRIMP: '/assets/images/tiny-pink-shrimp-trader.svg',
  LEVIATHAN: '/assets/images/black-leviathan-trader.svg',
  SETTING_NOTIFICATION_ICON: '/assets/images/notification-settings-icon.svg',
  SETTING_INTERFACE_ICON: '/assets/images/interface-settings-icon.svg',
  SETTING_LANGUAGE_ICON: '/assets/images/language-settings-icon.svg',
  SETTING_CHAT_ICON: '/assets/images/chat-settings-icon.svg',
  SETTING_AUDIO_ICON: '/assets/images/audio-settings-icon.svg',
  SETTING_RISK_ICON: '/assets/images/risk-settings-icon.svg',
  SETTING_RISK_ADJUST_ICON: '/assets/images/risk-management-pop-adjust.svg',
  SETTING_RISK_MANAGE_WARNING_ICON:
    '/assets/images/risk-manage-pop-warning.svg',
  REFER_ICON: '/assets/images/refer-icon.svg',
  EDIT_ICON: '/assets/images/edit-icon.svg',
  STAKETOKEN_ICON: '/assets/images/stake.svg',
  DEFAULT_ICON: '/assets/icons/missing-coin-light.svg',
  DEFAULT_ICON_DARK: '/assets/icons/missing-coin-dark.svg',
  EXPIRED_ICON: '/assets/images/expired.svg',
  LEVEL_ACCOUNT_ICON_1: '/assets/images/level-1.svg',
  LEVEL_ACCOUNT_ICON_2: '/assets/images/level-2.svg',
  LEVEL_ACCOUNT_ICON_3: '/assets/images/level-3.svg',
  LEVEL_ACCOUNT_ICON_4: '/assets/images/level-4.svg',
  LEVEL_ACCOUNT_ICON_5: '/assets/images/level-5.svg',
  LEVEL_ACCOUNT_ICON_6: '/assets/images/level-6.svg',
  LEVEL_ACCOUNT_ICON_7: '/assets/images/level-7.svg',
  LEVEL_ACCOUNT_ICON_8: '/assets/images/level-8.svg',
  LEVEL_ACCOUNT_ICON_9: '/assets/images/level-9.svg',
  LEVEL_ACCOUNT_ICON_10: '/assets/images/level-10.svg',
  HAP_ACCOUNT_ICON: '/assets/icons/hap-account-icon.svg',
  ACCOUNT_SUMMARY: '/assets/icons/account-icon-summary.svg',
  XHT_COIN_STACK: '/assets/images/XHT-coin-stack.svg',
  XHT_DOCS: '/assets/images/XHT-docs.svg',
  XHT_WAVES: '/assets/images/wave-icon.svg',
  XHT_EMAIL: '/assets/images/XHT-email.svg',
  XHT_FAQ: '/assets/images/XHT-FAQ.svg',
  XHT_PDF: '/assets/images/XHT-pdf.svg',
  REFERRAL_SUCCESS: '/assets/icons/send-request.svg',
  INCOMING_WAVE: '/assets/images/incoming-wave.svg',
  TRADE_ANNOUNCEMENT: '/assets/images/announcement.svg',
  CHAT_EMOJI: '/assets/icons/emoji-face-icon.svg',
  TRADE_SETTINGS: '/assets/images/spanner.svg',
  TRADE_WAVES: '/assets/images/wave-icon.svg',
  XHT_LOGO_LIGHT: '/assets/icons/XHT-logo-light.svg',
  XHT_LOGO_DARK: '/assets/icons/XHT-logo-dark.svg',
  BONUS_OFFERING: '/assets/icons/bonus_offering.svg',
  UP_ARROW: '/assets/images/buy-trade.svg',
  DOWN_ARROW: '/assets/images/sell-trade.svg',
  MOON_THEME: '/assets/icons/moon-theme.svg',
  SUN_THEME: '/assets/icons/sun-theme.svg',
  PLUGINS_CHAT: '/assets/plugins/plugin-chat.png',
  PLUGINS_FRESHDESK: '/assets/plugins/plugin-freshdesk.png',
  PLUGINS_LIQUIDITY: '/assets/plugins/plugin-liquidity.png',
  PLUGINS_SHUFTI: '/assets/plugins/plugin-shufti.png',
  PLUGINS_SMS: '/assets/plugins/plugin-sms.png',
  PLUGINS_VERIFICATION: '/assets/plugins/plugin-verification.png',
  PLUGINS_ZENDESK: '/assets/plugins/plugin-zendesk.png',
  PLUGINS_BANK: '/assets/plugins/plugin-bank.png',
  PLUGINS_VAULT: '/assets/plugins/plugin-vault.png',
  DEFAULT_PLUGINS: '/assets/plugins/default-plugin.png',
  HOLLAEX_INIT_LOGO: '/assets/images/hollaex-icon-01.svg',
  CANDLES_LOGO: '/assets/images/Light-theme-candles.svg',
  WALLET_BTC_ICON: '/assets/images/wallet-only-btc-icon.svg',
  SET_ADMIN_NETWORK_KEYS: '/assets/images/set-admin-network-keys.svg',
  SET_ADMIN_EMAIL: '/assets/images/set-admin-email.svg',
  SET_ADMIN_PASSWORD: '/assets/images/set-admin-password.svg',
  SET_ADMIN_RETYPE_PASSWORD: '/assets/images/set-admin-retype-password.svg',
  TIMEZONE_WORLD_MAP: '/assets/images/timezone-worldmap.svg',
  SETUP_SECTION_PRO_TRADING: '/assets/images/setup-section-pro-trading-01.svg',
  SETUP_SECTION_LOADING: '/assets/images/762.gif',
  SETUP_SECTION_BACKOFFICE: '/assets/images/setup-section-backoffice.svg',
  SETUP_SECTION_LIQUIDITY: '/assets/images/setup-section-liquidity.svg',
  SETUP_SECTION_QUICK_TRADE: '/assets/images/setup-section-quick-trade.svg',
  SETUP_SECTION_CRYPTO_WALLET: '/assets/images/setup-section-crypto-wallet.svg',
  SETUP_SECTION_PRICE_DISCOVERY: '/assets/images/setup-price-discovery.svg',
  SETUP_QUICK_TRADE: '/assets/images/initialize-quick-trade.svg',
  HEX_PATTERN_ICON: '/assets/icons/hex-pattern-icon-05.svg',
  GENERAL_SETUP: '/assets/images/general-setup.svg',
  USERS_SETUP: '/assets/images/users.svg',
  BLUE_SCREEN_EYE_ICON: '/assets/images/all-seeing-eye-admin-role-blue.png',
  BLUE_SCREEN_COMMUNICATON_SUPPORT_ROLE: '/assets/images/communications-role-seal-02.svg',
  BLUE_SCREEN_EXCHANGE_SUPPORT_ROLE: '/assets/images/exchange-support-role-01.svg',
  BLUE_SCREEN_SUPERVISOR: '/assets/images/supervisor.svg',
  BLUE_SCREEN_KYC: '/assets/images/KYC-01.svg',
  BLUE_SCREEN_LINK: '/assets/images/link.svg',
  USER_DETAILS_ICON: '/assets/images/user-info-details-page.svg',
  TWO_STEP_KEY_ICON: '/assets/images/2fa-01.svg',
  ACC_FREEZE: '/assets/images/freeze.svg',
  ACC_FLAG: '/assets/images/flag.svg',
  ADMIN_PLUGINS: '/assets/images/plugins.svg',
  ADMIN_TIERS: '/assets/images/tiers.svg',
  ADMIN_ROLES: '/assets/images/roles.svg',
  ADMIN_CUSTOMIZE: '/assets/images/customize.svg',
  ADMIN_MISSING_GO_BACK: '/assets/images/missing-page-go-back-to-dash.svg',
  HELP_DESCRIPTION_POPUP: '/assets/images/help-popup-description.png',
  HELP_FOOTER_POPUP: '/assets/images/help-popup-footer.png',
  DEPOSIT_TIERS_SECTION: '/assets/images/deposit-tier-section.svg',
  WITHDRAW_TIERS_SECTION: '/assets/images/withdraw-tier-section.svg',
  TAKER_TIERS_SECTION: '/assets/images/taker-tier-section.svg',
  MAKER_TIERS_SECTION: '/assets/images/maker-tier-section.svg',
  LIMITS_SECTION_ICON: '/assets/images/limits-coin-tiers.svg',
  FEES_SECTION_ICON: '/assets/images/limits-pairs-tiers.svg',
  SOCIAL_ICONS: {
    FACEBOOK: '/assets/icons/facebook.png',
    LINKEDIN: '/assets/icons/linkedin.png',
    TWITTER: '/assets/icons/twitter.png',
    INSTAGRAM: '/assets/icons/instagram.svg',
    TELEGRAM: '/assets/icons/telegram.png',
    GOOGLE: '/assets/icons/google.png',
    YOUTUBE: '/assets/icons/youtube.png'
  },

  FEATURES_ICONS: {
    PRO_TRADING: '/assets/images/features-pro-trade-icons.svg',
    PAYMENT: '/assets/images/features-payment-card-icons.svg',
    SECURITY: '/assets/images/features-lock-icons.svg',
    REPORTING: '/assets/images/features-data-icons.svg',
    SUPPORT: '/assets/images/features-support-icons.svg',
    LEGAL: '/assets/images/features-legal-icons.svg',
  },

  SUMMMARY_ICON: {
    LEVEL_1: '/assets/summary/level-1.png',
    LEVEL_1_DARK: '/assets/summary/level-1-dark.png',
    LEVEL_2: '/assets/summary/level-2.png',
    LEVEL_2_DARK: '/assets/summary/level-2-dark.png',
    LEVEL_3: '/assets/summary/level-3.png',
    LEVEL_3_DARK: '/assets/summary/level-3-dark.png',
    LEVEL_4: '/assets/summary/level-4.png',
    LEVEL_4_DARK: '/assets/summary/level-4-dark.png'
  }
};

const icons = flatten(nestedIcons, options)

export default icons;