{{- if .Values.autoScaling.hpa.enable }}

{{- $minReplicas := .Values.stable.replicaCount | int }}
{{- $maxReplicas := add 1 $minReplicas }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Release.Name}}
  minReplicas: {{ $minReplicas }}
  maxReplicas: {{ $maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.hpa.memory.threshold }}
        
{{- end }}