
// Generated by Selenium IDE
//testing the login function of Hollaex Kit
//Using Selenium webderiver and Mocha/Chai
//given, when and then
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const { expect } = require('chai');
const { Console } = require('console');
const path = require('path')
require('dotenv').config({ path: path.resolve(__dirname, '../.env') })
let userName = process.env.ADMIN_USER;
let passWord = process.env.ADMIN_PASS;
let logInPage = process.env.LOGIN_PAGE;
let Website = process.env.WEBSITE;
describe('Orders', function() {
	this.timeout(300000);
	let driver;
	let vars;
	function sleep(ms) {
		return new Promise((resolve) => {
			setTimeout(resolve, ms);
		});
	} 
	beforeEach(async function() {
		driver = await new Builder().forBrowser('chrome').build();
		vars = {};
		
		
	});
	afterEach(async function() {
	//	await driver.quit();
	});
  it('Untitled', async function() {
	  // Test name: Untitled
		// Step # | name | target | value
		// 1 | open | /account | 
		await driver.get(logInPage);
		await sleep(10000);
		// 2 | type | name=email | USER@bitholla.com
		// await driver.wait(until.elementLocated(await driver.findElement(By.name("email"))), 10000);
		await driver.findElement(By.name('email')).sendKeys(userName);
		// 3 | type | name=password | bitholla@bitholla.com
		//await driver.wait(until.elementLocated(await driver.findElement(By.name("password"))),5000);
		await driver.findElement(By.name('password')).sendKeys(passWord);
		// 4 | click | name=email | 
		
		await sleep(4000);
		await driver.findElement(By.name('email')).click();
		// 5 | click | css=.holla-button | 
		await driver.wait(until.elementIsEnabled(await driver.findElement(By.css('.holla-button'))), 50000);
		await driver.findElement(By.css('.holla-button')).click();
        await driver.manage().window().maximize();
	await sleep(10000);
	await driver.get(Website+'trade/xht-usdt')//("https://sandbox.hollaex.com/trade/xht-usdt")//
	  let text ='hi'
	await sleep(10000)
    let linkss = await driver.findElements(By.className("trade-col_side_wrapper flex-column d-flex apply_rtl"))//('table_body-row'))
    for(let link of linkss) {
        text = await link.getText();
        console.log("objec :"+ String(link))
        console.log("this is text:"+text);
    }

 console.log("this is text:");
    await driver.get("https://sandbox.hollaex.com/wallet")
	await sleep(10000)
    // let linksss = await driver.findElements(By.id('table_body-row'))
    // console.log("wallet"+linksss+"n")
       let linksss = await driver.findElements(By.className("mr-4"))//('table_body-row'))
    for(let link of linksss) {
        text = await link.getText();
        console.log("objec :"+ String(link))
        console.log("this is text:"+text);
    }
  })
})
