import STRINGS from '../../config/localizedStrings';

const { LOGIN, APP_TITLE, LOGIN_TEXT, FORM_FIELDS, VALIDATIONS } = STRINGS;

export const TEXTS = {
  TITLE: LOGIN_TEXT,
  LOGIN_TO: STRINGS.formatString(LOGIN.LOGIN_TO, APP_TITLE),
  CANT_LOGIN: LOGIN.CANT_LOGIN,
  NO_ACCOUNT: LOGIN.NO_ACCOUNT,
  CREATE_ACCOUNT: LOGIN.CREATE_ACCOUNT,
  HELP: LOGIN.HELP,
  FORM: {
    FIELDS: {
      email: {
        label: FORM_FIELDS.EMAIL_LABEL,
        placeholder: FORM_FIELDS.EMAIL_PLACEHOLDER,
      },
      password: {
        label: FORM_FIELDS.PASSWORD_LABEL,
        placeholder: FORM_FIELDS.PASSWORD_PLACEHOLDER,
      },
    },
    BUTTON: LOGIN_TEXT,
    VALIDATIONS: {
      OTP_LOGIN: VALIDATIONS.OTP_LOGIN,
      INVALID_EMAIL: VALIDATIONS.INVALID_EMAIL,
      TYPE_EMAIL: VALIDATIONS.TYPE_EMAIL,
    },
  },
}
