import STRINGS from '../../config/localizedStrings';
import { ICONS } from '../../config/constants';

const { FORM_FIELDS, VALIDATIONS, CONTACT_US_TEXT, VERIFICATION_EMAIL_REQUEST, VERIFICATION_EMAIL_REQUEST_SUCCESS } = STRINGS;

export const TEXTS = {
  TITLE: VERIFICATION_EMAIL_REQUEST.TITLE,
  ...VERIFICATION_EMAIL_REQUEST,
  FORM: {
    FIELDS: {
      email: {
        label: FORM_FIELDS.EMAIL_LABEL,
        placeholder: FORM_FIELDS.EMAIL_PLACEHOLDER,
      },
    },
    BUTTON: VERIFICATION_EMAIL_REQUEST.BUTTON,
    VALIDATIONS: {
      INVALID_EMAIL: VALIDATIONS.INVALID_EMAIL,
      TYPE_EMAIL: VALIDATIONS.TYPE_EMAIL,
    },
  },
}

export const VERIFICATION_RESEND_TEXTS = {
  ...VERIFICATION_EMAIL_REQUEST_SUCCESS,
  BUTTON: CONTACT_US_TEXT,
  ICON: ICONS.VERIFICATION_SENT,
}
