// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, './../../.env') });
let communicator = process.env.COMMUNICATOR;
let password = process.env.PASSWORD;
let logInPage = process.env.LOGIN_PAGE;

describe('communicator', function() {
	this.timeout(3000000);
	let driver;
	let vars;
	function sleep(ms) {
		return new Promise((resolve) => {
			setTimeout(resolve, ms);
		});
	}
	beforeEach(async function() {
		driver = await new Builder().forBrowser('chrome').build();
		driver.manage().window().maximize();

	});
	afterEach(async function() {
		await driver.quit();
	});
	it('communicator', async function() {
		console.log('Communicator can access to website direct editing for content management and communications');
		console.log(' Test name: communicator');
		console.log(' Step # | name | target | value');
		console.log(' 1 | open | /login | ');
		await driver.get(logInPage);
		await sleep(5000);
		console.log(' 2 | type | name=email |'+communicator);
		await driver.findElement(By.name('email')).sendKeys(communicator);
		console.log(' 3 | type | name=password | password');
		await driver.findElement(By.name('password')).sendKeys(password);
		console.log(' 4 | click | css=.holla-button | ');
		await sleep(5000);
		await driver.findElement(By.css('.holla-button')).click();
		await sleep(5000);
		console.log(' 5 | click | css=a > .pl-1 | ');
		await driver.findElement(By.css('a > .pl-1')).click();
		await sleep(5000);
		console.log(' 6 | click | linkText=Users | ');
		await driver.findElement(By.linkText('Users')).click();
		await sleep(5000);
		console.log(' 7 | click | id=rc-tabs-0-tab-userVerification | ');
		await driver.findElement(By.id('rc-tabs-0-tab-userVerification')).click();
		console.log(' 8 | click | css=.ant-empty-description | ');
		await sleep(5000);
		await driver.findElement(By.css('.ant-empty-description')).click();
		console.log(' 9 | assertText | css=.ant-empty-description | No Data');
		assert(await driver.findElement(By.css('.ant-empty-description')).getText() == 'No Data');
		console.log(' 10 | click | id=rc-tabs-0-tab-users | ');
		await driver.findElement(By.id('rc-tabs-0-tab-users')).click();
		console.log(' 11 | assertText | xpath=//*[@id=\'rc-tabs-0-panel-users\']/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td/div/p | No Data');
		await sleep(5000);
		assert(await driver.findElement(By.xpath('//*[@id="rc-tabs-0-panel-users"]/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td/div/p')).getText() == 'No Data');
		console.log(' 12 | click | linkText=Financials | ');
		await driver.findElement(By.linkText('Financials')).click();
		console.log(' 13 | click | css=.content-wrapper | ');
		await driver.findElement(By.css('.content-wrapper')).click();
		console.log(' 14 | assertText | css=p | -Access denied: User is not authorized to access this endpoint-');
		await sleep(5000);
		assert(await driver.findElement(By.css('p')).getText() == '-Access denied: User is not authorized to access this endpoint-');
		console.log(' 15 | click | css=.ant-card-body > .ant-alert | ');
		await driver.findElement(By.css('.ant-card-body > .ant-alert')).click();
		console.log(' 16 | assertText | css=.ant-card-body .ant-alert-description | Access denied: User is not authorized to access this endpoint');
		await sleep(5000);
		assert(await driver.findElement(By.css('.ant-card-body .ant-alert-description')).getText() == 'Access denied: User is not authorized to access this endpoint');
		console.log(' 17 | click | id=rc-tabs-1-tab-assets | ');
		await driver.findElement(By.id('rc-tabs-1-tab-assets')).click();
		console.log(' 18 | click | css=.content | ');
		await driver.findElement(By.css('.content')).click();
		console.log(' 19 | assertText | css=.content | To view this page you must go back to Holla Dash');
		await sleep(5000);
		assert(await driver.findElement(By.css('.content')).getText() == 'To view this page you must go back to Holla Dash');
		console.log(' 20 | click | id=rc-tabs-1-tab-deposits | ');
		await driver.findElement(By.id('rc-tabs-1-tab-deposits')).click();
		console.log(' 21 | click | css=.ant-alert-closable | ');
		await sleep(5000);
		await driver.findElement(By.css('.ant-alert-closable')).click();
		console.log(' 22 | assertText | css=.ant-alert-closable > .ant-alert-message | Access denied: User is not authorized to access this endpoint');
		assert(await driver.findElement(By.css('.ant-alert-closable > .ant-alert-message')).getText() == 'Access denied: User is not authorized to access this endpoint');
		console.log(' 23 | click | id=rc-tabs-1-tab-withdrawals | ');
		await driver.findElement(By.id('rc-tabs-1-tab-withdrawals')).click();
		await sleep(5000);
		console.log(' 24 | click | css=#rc-tabs-1-panel-withdrawals .app-wrapper > .ant-alert | ');
		await driver.findElement(By.css('#rc-tabs-1-panel-withdrawals .app-wrapper > .ant-alert')).click();
		console.log(' 25 | assertText | css=#rc-tabs-1-panel-withdrawals .app-wrapper > .ant-alert > .ant-alert-message | Access denied: User is not authorized to access this endpoint');
		assert(await driver.findElement(By.css('#rc-tabs-1-panel-withdrawals .app-wrapper > .ant-alert > .ant-alert-message')).getText() == 'Access denied: User is not authorized to access this endpoint');
	});
});
